services:
  postgres:
    image: postgres:latest  # Usa la última versión de PostgreSQL
    container_name: todos-db  # Nombre del contenedor
    environment:
      POSTGRES_USER: admin  # Nombre de usuario para PostgreSQL
      POSTGRES_PASSWORD: admin_password  # Contraseña del usuario
      POSTGRES_DB: todosDB  # Nombre de la base de datos por defecto
    ports:
      - "5432:5432"  # Expone el puerto 5432 para conexiones locales
    volumes:
      - postgres:/var/lib/postgresql/data  # Almacena los datos de PostgreSQL de forma persistente

volumes:
  postgres:
    driver: local  # Volumen local para almacenar los datos de PostgreSQL
